//import { NextApiRequest, NextApiResponse } from "next";
//https://products.aspose.app/cells/pt/conversion
//export default function Products(request: NextApiRequest, response: NextApiResponse) {
//return response.json(products)
//}

export const products = [
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 1,
        "name": "Amelie",
        "image": "/assets/crepe01.jpeg",
        "price": 15,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 2,
        "name": "Chaumont",
        "image": "/assets/crepe02.jpeg",
        "price": 30,
        "active": "Sim",
        "ingredients": ["Bouef"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 3,
        "name": "Courbevoie",
        "image": "/assets/crepe01.jpeg",
        "price": 30,
        "active": "Sim",
        "ingredients": ["Charcuterie"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 4,
        "name": "Empereur de la Mer",
        "image": "/assets/crepe02.jpeg",
        "price": 45,
        "active": "Sim",
        "ingredients": ["Fruits de Mer"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 5,
        "name": "Estrasburgo",
        "image": "/assets/crepe01.jpeg",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Bouef"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 6,
        "name": "Eze",
        "image": "/assets/crepe02.jpeg",
        "price": 45,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 7,
        "name": "Linguine",
        "image": "/assets/crepe01.jpeg",
        "price": 23,
        "active": "Sim",
        "ingredients": ["Vegetariens"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 8,
        "name": "Louvre",
        "image": "/assets/crepe02.jpeg",
        "price": 25,
        "active": "Sim",
        "ingredients": ["Poulet"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 9,
        "name": "Lyon",
        "image": "/assets/crepe01.jpeg",
        "price": 33,
        "active": "Sim",
        "ingredients": ["Bouef"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 10,
        "name": "Marseille",
        "image": "/assets/crepe02.jpeg",
        "price": 15,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 11,
        "name": "MontMartre",
        "image": "/assets/crepe01.jpeg",
        "price": 14,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 12,
        "name": "MontPellier",
        "image": "/assets/crepe02.jpeg",
        "price": 28,
        "active": "Sim",
        "ingredients": ["Poulet"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 13,
        "name": "Moulin Rouge",
        "image": "/assets/crepe01.jpeg",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 14,
        "name": "Paris",
        "image": "/assets/crepe02.jpeg",
        "price": 25,
        "active": "Sim",
        "ingredients": ["Charcuterie"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 15,
        "name": "Puebla",
        "image": "/assets/crepe01.jpeg",
        "price": 15,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 16,
        "name": "Rennes",
        "image": "/assets/crepe02.jpeg",
        "price": 25,
        "active": "Sim",
        "ingredients": ["Charcuterie"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 17,
        "name": "Sacre-Couer",
        "image": "/assets/crepe01.jpeg",
        "price": 20,
        "active": "Sim",
        "ingredients": ["Vegetariens"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 18,
        "name": "Saint Lazare",
        "image": "/assets/crepe02.jpeg",
        "price": 25,
        "active": "Sim",
        "ingredients": ["Charcuterie"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 19,
        "name": "Toulouse",
        "image": "/assets/crepe01.jpeg",
        "price": 12,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 20,
        "name": "Tour Eiffel",
        "image": "/assets/crepe02.jpeg",
        "price": 36,
        "active": "Sim",
        "ingredients": ["Bouef"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 21,
        "name": "Trapiche",
        "image": "/assets/crepe01.jpeg",
        "price": 120,
        "active": "Sim",
        "ingredients": ["Massa,Recheio"],
        "time": "10 min"
    },
    {
        "category_id": 1,
        "category_name": "Crepe",
        "id": 22,
        "name": "Triomphe",
        "image": "/assets/crepe02.jpeg",
        "price": 40,
        "active": "Sim",
        "ingredients": ["Fruits de Mer"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 23,
        "name": "Camarão Internacional",
        "image": "/assets/prato01.jpg",
        "price": 42,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 24,
        "name": "Camarao Internacional Executivo",
        "image": "/assets/prato01.jpg",
        "price": 39,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 25,
        "name": "Crepe México",
        "image": "/assets/nocrepe.jpg",
        "price": 29.9,
        "active": "Não",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 26,
        "name": "Entrecot executivo",
        "image": "/assets/entrecot.jpg",
        "price": 39,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 27,
        "name": "Entrecot",
        "image": "/assets/entrecot.jpg",
        "price": 55,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 28,
        "name": "Filet Moses",
        "image": "/assets/logotipo01.png",
        "price": 55,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 29,
        "name": "Fresh Day",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Não",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 30,
        "name": "Le Caché",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 31,
        "name": "Moqueca Veggie",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 32,
        "name": "Omelete recheada de queijo tomate",
        "image": "/assets/logotipo01.png",
        "price": 19,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 33,
        "name": "Parmegiana de carne",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 34,
        "name": "Parmegiana de frango",
        "image": "/assets/logotipo01.png",
        "price": 19,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 35,
        "name": "Parmegiano",
        "image": "/assets/logotipo01.png",
        "price": 39,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 36,
        "name": "Penne com Frango",
        "image": "/assets/logotipo01.png",
        "price": 25,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 37,
        "name": "Sopa de Cebola",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 38,
        "name": "Spagheti a Bolognese",
        "image": "/assets/logotipo01.png",
        "price": 26,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 39,
        "name": "Talharim com Camarão",
        "image": "/assets/logotipo01.png",
        "price": 42,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 2,
        "category_name": "Pratos",
        "id": 40,
        "name": "Tilapia empanada com molho pariense",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Molho, acompanhamento"],
        "time": "10 min"
    },
    {
        "category_id": 3,
        "category_name": "Sobremesas",
        "id": 41,
        "name": "Brownie de Colher",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Bolo, cobertura"],
        "time": "10 min"
    },
    {
        "category_id": 3,
        "category_name": "Sobremesas",
        "id": 42,
        "name": "Creme Blanc",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Bolo, cobertura"],
        "time": "10 min"
    },
    {
        "category_id": 3,
        "category_name": "Sobremesas",
        "id": 43,
        "name": "Creme Brulee",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Bolo, cobertura"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 44,
        "name": "Agua",
        "image": "/assets/logotipo01.png",
        "price": 6,
        "active": "Sim",
        "ingredients": ["Água"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 45,
        "name": "Bonne Vie",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Água,Sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 46,
        "name": "Caipirinha",
        "image": "/assets/logotipo01.png",
        "price": 14,
        "active": "Sim",
        "ingredients": ["Cachaça, limão, açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 47,
        "name": "Cha Gelado",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 48,
        "name": "Chá Quente",
        "image": "/assets/logotipo01.png",
        "price": 3,
        "active": "Não",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 49,
        "name": "Chandon",
        "image": "/assets/logotipo01.png",
        "price": 180,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 50,
        "name": "Gin Tônica",
        "image": "/assets/logotipo01.png",
        "price": 21,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 51,
        "name": "Gin Tônica Saborizada",
        "image": "/assets/logotipo01.png",
        "price": 22,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 52,
        "name": "Heineken/Corona",
        "image": "/assets/logotipo01.png",
        "price": 12,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 53,
        "name": "Lagoa Azul",
        "image": "/assets/logotipo01.png",
        "price": 21,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 54,
        "name": "Limonada Suiça",
        "image": "/assets/logotipo01.png",
        "price": 14,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 55,
        "name": "Limoneto",
        "image": "/assets/logotipo01.png",
        "price": 8,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 56,
        "name": "Long Neck",
        "image": "/assets/logotipo01.png",
        "price": 9,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 57,
        "name": "Maracujovisk",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 58,
        "name": "Melancita",
        "image": "/assets/logotipo01.png",
        "price": 23,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 59,
        "name": "Mojito",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 60,
        "name": "Morangovisk",
        "image": "/assets/logotipo01.png",
        "price": 18,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 61,
        "name": "Pina Colada",
        "image": "/assets/logotipo01.png",
        "price": 22,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 62,
        "name": "Preparo Cozumel",
        "image": "/assets/logotipo01.png",
        "price": 5,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 63,
        "name": "Rafraichissant",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 64,
        "name": "Ref. H2O Limoneto c/Gas Pet",
        "image": "/assets/logotipo01.png",
        "price": 8,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 65,
        "name": "Refri Lata",
        "image": "/assets/logotipo01.png",
        "price": 6,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 66,
        "name": "Reservado",
        "image": "/assets/logotipo01.png",
        "price": 90,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 67,
        "name": "Roselle",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 68,
        "name": "Sex on the beach",
        "image": "/assets/logotipo01.png",
        "price": 26,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 69,
        "name": "Soda Italiana",
        "image": "/assets/logotipo01.png",
        "price": 12,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 70,
        "name": "Suco Natural",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 4,
        "category_name": "Bebidas",
        "id": 71,
        "name": "Vinho Poeme Cabernet Sauvignon Syrah 750Ml",
        "image": "/assets/logotipo01.png",
        "price": 150,
        "active": "Sim",
        "ingredients": ["Água, sabor"],
        "time": "10 min"
    },
    {
        "category_id": 5,
        "category_name": "Saladas",
        "id": 72,
        "name": "Salada Caeser da Casa",
        "image": "/assets/logotipo01.png",
        "price": 25,
        "active": "Sim",
        "ingredients": ["Folha1, folha2"],
        "time": "10 min"
    },
    {
        "category_id": 5,
        "category_name": "Saladas",
        "id": 73,
        "name": "Salada Caprese",
        "image": "/assets/logotipo01.png",
        "price": 21,
        "active": "Sim",
        "ingredients": ["Folha1, folha2"],
        "time": "10 min"
    },
    {
        "category_id": 5,
        "category_name": "Saladas",
        "id": 74,
        "name": "Salada de Salmão",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Não",
        "ingredients": ["Folha1, folha2"],
        "time": "10 min"
    },
    {
        "category_id": 5,
        "category_name": "Saladas",
        "id": 75,
        "name": "Salada Simples",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Folha1, folha2"],
        "time": "10 min"
    },
    {
        "category_id": 6,
        "category_name": "Pastas",
        "id": 76,
        "name": "Penne ao Funghi",
        "image": "/assets/logotipo01.png",
        "price": 32,
        "active": "Sim",
        "ingredients": ["Ingred01, ingred02"],
        "time": "10 min"
    },
    {
        "category_id": 7,
        "category_name": "Fondue",
        "id": 77,
        "name": "Adicional fondue",
        "image": "/assets/logotipo01.png",
        "price": 8,
        "active": "Não",
        "ingredients": ["Ingred01, ingred02"],
        "time": "10 min"
    },
    {
        "category_id": 7,
        "category_name": "Fondue",
        "id": 78,
        "name": "Fondue adc",
        "image": "/assets/logotipo01.png",
        "price": 7,
        "active": "Sim",
        "ingredients": ["Ingred01, ingred02"],
        "time": "10 min"
    },
    {
        "category_id": 7,
        "category_name": "Fondue",
        "id": 79,
        "name": "Fondue Doce",
        "image": "/assets/logotipo01.png",
        "price": 69,
        "active": "Sim",
        "ingredients": ["Ingred01, ingred02"],
        "time": "10 min"
    },
    {
        "category_id": 7,
        "category_name": "Fondue",
        "id": 80,
        "name": "Fondue Queijo",
        "image": "/assets/logotipo01.png",
        "price": 109,
        "active": "Sim",
        "ingredients": ["Ingred01, ingred02"],
        "time": "10 min"
    },
    {
        "category_id": 7,
        "category_name": "Fondue",
        "id": 81,
        "name": "Salada Toulon",
        "image": "/assets/logotipo01.png",
        "price": 19,
        "active": "Sim",
        "ingredients": ["Ingred01, ingred02"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 82,
        "name": "Adicional Camarão",
        "image": "/assets/logotipo01.png",
        "price": 15,
        "active": "Não",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 83,
        "name": "Arroz",
        "image": "/assets/logotipo01.png",
        "price": 10,
        "active": "Sim",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 84,
        "name": "Bacon",
        "image": "/assets/logotipo01.png",
        "price": 6,
        "active": "Sim",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 85,
        "name": "Batata",
        "image": "/assets/logotipo01.png",
        "price": 6,
        "active": "Sim",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 86,
        "name": "Batata cheddar e bacon",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 87,
        "name": "Calabresa acebolada com tomate",
        "image": "/assets/logotipo01.png",
        "price": 37,
        "active": "Sim",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 88,
        "name": "Legume",
        "image": "/assets/logotipo01.png",
        "price": 23,
        "active": "Sim",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 8,
        "category_name": "Adicionais",
        "id": 89,
        "name": "Massa Especial",
        "image": "/assets/logotipo01.png",
        "price": 3,
        "active": "Não",
        "ingredients": ["Item01, sal ou açúcar"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 90,
        "name": "Combo Chaumont",
        "image": "/assets/logotipo01.png",
        "price": 42,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 91,
        "name": "Combo Corbevoie",
        "image": "/assets/logotipo01.png",
        "price": 42,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 92,
        "name": "Combo Estrasburgo",
        "image": "/assets/logotipo01.png",
        "price": 47,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 93,
        "name": "Combo Legume",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 94,
        "name": "Combo Linguine",
        "image": "/assets/logotipo01.png",
        "price": 35,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 95,
        "name": "Combo Louvre",
        "image": "/assets/logotipo01.png",
        "price": 37,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 96,
        "name": "Combo Lyon",
        "image": "/assets/logotipo01.png",
        "price": 45,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 97,
        "name": "Combo Montpellier",
        "image": "/assets/logotipo01.png",
        "price": 40,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 98,
        "name": "Combo Rennes",
        "image": "/assets/logotipo01.png",
        "price": 37,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 99,
        "name": "Combo Sacre-Couer",
        "image": "/assets/logotipo01.png",
        "price": 32,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 100,
        "name": "Combo Saint Lazare",
        "image": "/assets/logotipo01.png",
        "price": 37,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 101,
        "name": "Combo Tour Eiffel",
        "image": "/assets/logotipo01.png",
        "price": 48,
        "active": "Sim",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 9,
        "category_name": "Combo",
        "id": 102,
        "name": "Halloween 4 Pessoas",
        "image": "/assets/logotipo01.png",
        "price": 272,
        "active": "Não",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 10,
        "category_name": "Promoção",
        "id": 103,
        "name": "Promoção da segunda feira",
        "image": "/assets/logotipo01.png",
        "price": 19.9,
        "active": "Não",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    },
    {
        "category_id": 10,
        "category_name": "Promoção",
        "id": 104,
        "name": "Promoção do dia",
        "image": "/assets/logotipo01.png",
        "price": 19.9,
        "active": "Não",
        "ingredients": ["Produto1, produto2"],
        "time": "10 min"
    }
]


export const orders = [
    {
        "id": 1,
        "order": 1,
        "place": 2,
        "cliente": "Osmair",
        "products": [{
            "category_id": 1,
            "category_name": "Crepe",
            "id": 1,
            "name": "Amelie",
            "image": "/assets/crepe01.jpeg",
            "price": 15,
            "active": "Sim",
            "ingredients": ["Massa,Recheio"],
            "time": "10 min"
        },
        {
            "category_id": 1,
            "category_name": "Crepe",
            "id": 2,
            "name": "Chaumont",
            "image": "/assets/crepe02.jpeg",
            "price": 30,
            "active": "Sim",
            "ingredients": ["Bouef"],
            "time": "10 min"
        },
        {
            "category_id": 1,
            "category_name": "Crepe",
            "id": 3,
            "name": "Courbevoie",
            "image": "/assets/crepe01.jpeg",
            "price": 30,
            "active": "Sim",
            "ingredients": ["Charcuterie"],
            "time": "10 min"
        }],
        "amount": 4,
        "price": 90
    },
    {
        "id": 2,
        "order": 2,
        "place": 2,
        "cliente": "Wanessa",
        "products": [
            {
                "category_id": 1,
                "category_name": "Crepe",
                "id": 8,
                "name": "Louvre",
                "image": "/assets/crepe02.jpeg",
                "price": 25,
                "active": "Sim",
                "ingredients": ["Poulet"],
                "time": "10 min"
            },
            {
                "category_id": 1,
                "category_name": "Crepe",
                "id": 9,
                "name": "Lyon",
                "image": "/assets/crepe01.jpeg",
                "price": 33,
                "active": "Sim",
                "ingredients": ["Bouef"],
                "time": "10 min"
            }
        ],
        "amount": 1,
        "price": 18.9
    },
    {
        "id": 3,
        "order": 3,
        "place": 3,
        "cliente": "Moises",
        "products": [
            {
                "category_id": 9,
                "category_name": "Combo",
                "id": 100,
                "name": "Combo Saint Lazare",
                "image": "/assets/logotipo01.png",
                "price": 37,
                "active": "Sim",
                "ingredients": ["Produto1, produto2"],
                "time": "10 min"
            },
            {
                "category_id": 9,
                "category_name": "Combo",
                "id": 101,
                "name": "Combo Tour Eiffel",
                "image": "/assets/logotipo01.png",
                "price": 48,
                "active": "Sim",
                "ingredients": ["Produto1, produto2"],
                "time": "10 min"
            },
            {
                "category_id": 9,
                "category_name": "Combo",
                "id": 102,
                "name": "Halloween 4 Pessoas",
                "image": "/assets/logotipo01.png",
                "price": 272,
                "active": "Não",
                "ingredients": ["Produto1, produto2"],
                "time": "10 min"
            }
        ],
        "amount": 2,
        "price": 357
    },
]

